CREATE DATABASE  IF NOT EXISTS `elearndatabase` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `elearndatabase`;

DROP TABLE IF EXISTS `course`;
CREATE TABLE `course` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `title` varchar(45) DEFAULT NULL,
  `author` varchar(45) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(11) DEFAULT NULL,
  `img` varchar(2083)  DEFAULT NULL,
  `video` varchar(2083)  DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1;

INSERT INTO `course` VALUES 
	(1, 'SQL-1. ДЕРЕКТЕР ҚОРЫНА КІРІСПЕ', 'Турганов Мадияр', 'Бұл курста SQL (Structured Query Language) жүйесінің негіздерін оқыңыз. SQL, деректерді сақтау және өңдеу, мәліметтерді іздеу, өзгерту және жою процесін жүзеге асыруға мүмкіндік беретін құралдық программалау жүйесі. Курстың мақсаты - деректер базаларымен жұмыс істеу мүмкіндіктерін беру және SQL-ді пайдалану әдістемесін оқыту.', 'IT','https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1715&q=80','https://www.youtube.com/watch?v=-3f6vNKIOoM'),
    (2, 'Web жобалау кіріспе - HTML','Турганов Мадияр','Бұл курс арқылы HTML (HyperText Markup Language) үшін мәндерді жазу мен пайдалану туралы біліміңізді шығарасыз. HTML өнімдерін құру және өңдеу, веб-беттерді жасау және пайдалану процесін жүзеге асыруға мүмкіндік беретін технологиялық тіл. Онлайн курс оқушыларға HTML-ді пайдалану әдістемесін оқыту және веб-беттерді жасау үшін көрсеткіштердің қалыптасуына қатысты мәліметтерді қамтамасыз ету мақсатын құрайды.','IT', 'https://images.unsplash.com/photo-1585076641399-5c06d1b3365f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 'https://www.youtube.com/watch?v=tEX7MKPxSGE'),
   	(3, 'WEB ЖОБАЛАУ. JavaScript.', 'АҚЖОЛ КНЯЗОВ', 'Бұл курс арқылы JavaScript құралын пайдалану туралы біліміңізді шығарасыз. JavaScript, веб-беттерді құру мен өңдеу, ағымдағы веб-технологияларымен қамтылған динамик құралдар мен интерактивті элементтерді жасауға мүмкіндік беретін скрипттік тіл.', 'IT', 'https://images.unsplash.com/photo-1592609931095-54a2168ae893?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 'https://www.youtube.com/watch?v=jKJr2FkD_yY'),
    (4, 'Python. Информатика ҰБТ', 'АҚЖОЛ КНЯЗОВ', 'Бұл курс арқылы Python құралын және оның қолданылуы туралы біліміңізді шығарасыз. Python, деректерді ағымдағы технологияларда өңдеуге мүмкіндік беретін жобалау тілі. Онлайн курс оқушыларға Python-дың негізін үйрету, өзіндік алгоритмдер жасау және Python қолдану арқылы өз проекттерін жүзеге асыруға мүмкіндік береді.', 'IT', 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2832&q=80', 'https://www.youtube.com/watch?v=IlDjVeblr5Q&list=PLnuQTiMgs5mYTnd2QjTYJ-tAG5P7N7bmx'),
    (5, 'Java программалау тілі', 'Нуржан Абдикарим', 'Бұл курс арқылы Java құралын және оның қолданылуы туралы біліміңізді шығарасыз. Java, технологиялық жобалау үшін қол жетімді, динамик, бәрінен алыс үшін қолдау көрсететін бір программа тілі. Онлайн курс оқушыларға Java-ның үнемі мүмкіндіктерін оқыту, оларды пайдалану, өз проекттерін жасау және оларды жүзеге асыруға мүмкіндік береді.', 'IT', 'https://images.unsplash.com/photo-1585332889055-059af80a9b5f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1064&q=80', 'https://www.youtube.com/watch?v=Oy8iUj-t0ME'),
	(7, 'ГЕОГРАФИЯ', 'Juz40 Online', 'Бұл курс арқылы оқушыларға географиялық жоспарлау туралы толық құрылымды мағлұмат беріледі. Осы курсты оқушылар өндіріс, жайлы қысқаша мәлімет алған кезде, оларға мұндағы мүмкіндіктер жайлы мағлұмат беріледі: географиялық танымдық, өнімдер және серіктестік, қалалық және аймақтық жоспарлау, орналасу, транспорт, энергетика, ауыл шаруашылығы және экологиялық мәселелер.', 'School', 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 'https://www.youtube.com/watch?v=DkL5AnXOSg8&list=PLI7N2qOEOVZrTUS4ARf33skJNHCqb7s7b'),
    (8, 'ҚАЗАҚСТАН ТАРИХЫ', 'Juz40 Online', 'Бұл курс арқылы оқушыларға Қазақстан тарихына толық түсінік беріледі. Курстағы мәзірлердің көмегімен оқушылар Қазақстан тарихының бастапқы кезеңдерінен бастап қазіргі кезгі тарихқа дейінгі даму қалыптасуын түсінеді. Оларға Қазақстан тарихының маңызды кезеңдері, дәуірлері, әскери және саяси тарихы, қоғамдық, культурлық және иелерімен байланысты аймақтардың тарихы, осы тарихтың артықшылықтары және мәнін түсіндіру мүмкіндігі беріледі.', 'School', 'https://images.unsplash.com/photo-1447069387593-a5de0862481e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2069&q=80', 'https://www.youtube.com/watch?v=2Cak1B2CDXM&list=PLI7N2qOEOVZpavFNozn67whQ3lNxJ95KK'),
    (9, 'Салалас құрмалас сөйлем', 'Juz40 Online', 'Бұл курс арқылы оқушыларға сөйлем туралы толық құрылымды мағлұмат беріледі. Курс арқылы оқушыларға сөйлемнің түрлерін, түсіндіруін, бұрышты құрмаласын, сөйлемнің мақсатын, функцияларын, түрлерін және олардың қолданылуын талдайды.', 'School', 'https://plus.unsplash.com/premium_photo-1681494534621-11a6a21f1fa3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 'https://www.youtube.com/watch?v=73OvMm8kmu8&list=PLI7N2qOEOVZo7vD0KXTjhRroGN761GDLx'),
    (10, 'ХИМИЯ', 'Juz40 Online', 'Бұл курс арқылы оқушыларға химия туралы толық түсінік беріледі. Курстағы мәзірлердің көмегімен оқушылар химиялық элементтердің, химиялық реакциялардың, химиялық қоспалардың, құрамдылық тәртібінің және басқа мәселелерінің түсінуін меңгереді.', 'School', 'https://images.unsplash.com/photo-1554475901-4538ddfbccc2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2072&q=80', 'https://www.youtube.com/watch?v=emd7uRNj-ys&list=PLI7N2qOEOVZo75MsNnKx_HL_H1EvOLnQe'),
    (11, 'Биология', 'Juz40 Online', 'Бұл курс арқылы оқушыларға биология туралы толық түсінік беріледі. Осы курс арқылы оқушылар асқазан, ботаника және зоология тақырыптарын талдайды. Осы курстың мақсаты, оқушыларға жан-жақты биологиялық мәселелердің түсінігін меңгерту, және оларды практикалық әдістемелер арқылы түсіну.', 'School', 'https://images.unsplash.com/photo-1625608914244-af9b2fe5f757?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80', 'https://www.youtube.com/watch?v=A0cKTx1uuI0&list=PLI7N2qOEOVZoSQz_3c1aU-nHZknaVlUTb'),
    (12, 'МАТЕМАТИКА', 'Juz40 Online', 'Осы курстың арқылы оқушылар математиканың негізгі пондерацияларын, теориясын және әдістерін меңгеру, сипаттауларын және қосымша материалдарды үйрену. Курста оқушылар математикалық модельдерді құру мен оларды пайдалану үшін қажетті түсініктерді меңгеру үшін оқытатылады.', 'School', 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 'https://www.youtube.com/watch?v=MLXH01W1iLY&list=PLI7N2qOEOVZoTXX0NOR-vKOMemMoWnSLl'),
    (13, 'ФИЗИКА', 'Juz40 Online', 'Осы курстың мақсаты, оқушыларға физикалық концепцияларды, теорияларды және әдістерді меңгерту және қолдануға болатын жолдарды оңай түсіну. Курста оқушылар физикалық жүйелердің құрамын, электромагниттік тұрғыдан және физикалық қуатты өлшемдерді меңгеру үшін оқытатылады.', 'School', 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80', 'https://www.youtube.com/watch?v=GLHsmQhHvq8&list=PLI7N2qOEOVZo6koixBILeK6ObrgRSrxL4'),
    (14, 'Биология ЕНТ', 'Juz40 Online', 'Бұл курс арқылы оқушыларға биология тесттеріне дайындалуға көмектеседі. Курс бойынша оқушылар биологиялық концепциялар, принциптер мен модельдер туралы толық түсінікке ие болады.', 'School', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80', 'https://www.youtube.com/watch?v=d0obS0JhLYM'),
    (15, 'ҰБТ', 'Juz40 Online', 'Бұл курста студенттер тесттің түрлерін, міндеттерін және жауаптарды қалай қайталауға боладынын түсінеді. Курстың негізгі мақсаты - тесті бойынша сынақтау және бастапқы үлгілерге жауап беру мүмкіндігін арттыру.', 'School', 'https://images.unsplash.com/photo-1560785477-d43d2b34e0df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80', 'https://www.youtube.com/watch?v=PQmd4FXelBo');